import { createHash } from 'node:crypto';
import AppError from './error.js';
import { sanitiseFilename } from './file-helpers.js';
import { createAssetStore } from './asset-store.js';
import type { GcodeFile, GcodeMetadata } from '../models/index.js';

const GCODE_MAGIC_RE = /^[GM]\d+/m;

export interface UploadGcodeOptions {
  filename: string;
  buffer: Buffer;
  uploadedByUserId: string;
}

/**
 * Validates magic bytes so someone can't sneak a non-G-code binary past
 * our size limit. Parses the first chunk as UTF-8 and scans for any
 * `G<digit>` / `M<digit>` line — matches every slicer we've seen (Cura,
 * PrusaSlicer, OrcaSlicer), plus hand-rolled G-code.
 */
function assertGcodeMagic(buffer: Buffer): void {
  const probe = buffer.subarray(0, Math.min(buffer.length, 1024)).toString('utf8');
  if (!GCODE_MAGIC_RE.test(probe)) {
    throw AppError.badRequest(
      'Datei sieht nicht wie G-Code aus (erwartet G/M-Kommandos in den ersten 1 KB).',
      'BAD_GCODE_MAGIC'
    );
  }
}

/**
 * Parses the slicer-emitted comment headers every major slicer prints
 * at the top of the file. Best-effort — any missing field is just left
 * off the returned object. Only the first 64 KB are scanned.
 */
function parseMetadata(buffer: Buffer): GcodeMetadata {
  const head = buffer.subarray(0, Math.min(buffer.length, 65536)).toString('utf8');
  const md: GcodeMetadata = {};

  // Cura: `;TIME:1234`, PrusaSlicer: `; estimated printing time (normal mode) = 1h 23m 4s`
  const timeCura = /^;TIME:(\d+)/m.exec(head);
  if (timeCura) md.estimatedSeconds = Number.parseInt(timeCura[1], 10);
  if (md.estimatedSeconds === undefined) {
    const timePrusa = /estimated printing time[^=]*=\s*(?:(\d+)d\s*)?(?:(\d+)h\s*)?(?:(\d+)m\s*)?(?:(\d+)s)?/i.exec(head);
    if (timePrusa) {
      const [, d, h, m, s] = timePrusa;
      const total =
        (Number.parseInt(d || '0', 10) * 86400) +
        (Number.parseInt(h || '0', 10) * 3600) +
        (Number.parseInt(m || '0', 10) * 60) +
        Number.parseInt(s || '0', 10);
      if (total > 0) md.estimatedSeconds = total;
    }
  }

  const filament = /;Filament used:\s*([\d.]+)\s*m/i.exec(head) || /filament used \[mm\]\s*=\s*([\d.]+)/i.exec(head);
  if (filament) {
    const value = Number.parseFloat(filament[1]);
    md.filamentMeters = filament[0].includes('[mm]') ? value / 1000 : value;
  }

  const grams = /;Filament weight:\s*([\d.]+)/i.exec(head) || /filament used \[g\]\s*=\s*([\d.]+)/i.exec(head);
  if (grams) md.filamentGrams = Number.parseFloat(grams[1]);

  const layers = /;LAYER_COUNT:(\d+)/.exec(head) || /;\s*total layer number:\s*(\d+)/i.exec(head);
  if (layers) md.layerCount = Number.parseInt(layers[1], 10);

  const slicer = /;generated by\s+(\S+)/i.exec(head);
  if (slicer) md.slicer = slicer[1];

  return md;
}

const store = createAssetStore<GcodeFile>({
  table: 'gcode_file',
  contentTable: 'gcode_file_content'
});

export class GcodeService {
  /**
   * Validates G-code magic bytes, parses slicer metadata,
   * deduplicates by SHA-256 and stores the bytea atomically. Identical
   * re-upload returns the existing row — no new content blob written.
   *
   * Owner attribution: the FIRST uploader of a given hash keeps the
   * row. Later uploaders just hit dedup and never get authorship.
   * Same behaviour as STL — dedup wins over attribution because the
   * content is identical anyway.
   */
  async uploadGcode(options: UploadGcodeOptions): Promise<GcodeFile> {
    const { filename, buffer, uploadedByUserId } = options;

    assertGcodeMagic(buffer);

    const cleanName = sanitiseFilename(filename, 'print.gcode');
    const sha256 = createHash('sha256').update(buffer).digest('hex');
    const metadata = parseMetadata(buffer);

    return store.withTx(async (client) => {
      const existing = await store.findBySha256(client, sha256);
      if (existing) return existing;
      return store.insertContent(client, {
        uploadedByUserId,
        filename: cleanName,
        sha256,
        sizeBytes: buffer.length,
        metadata,
        content: buffer
      });
    });
  }

  // The plain CRUD now lives in the store factory — these are thin
  // arrow re-exports so existing callers keep their imports.
  // ON DELETE CASCADE wipes the content row; the print_job FK uses
  // RESTRICT, so the controller surfaces 23503 → 409 if the file is
  // still referenced.
  listForUser = (userId: string, limit = 50, offset = 0): Promise<GcodeFile[]> =>
    store.list(userId, limit, offset);
  getById = (id: string): Promise<GcodeFile | null> => store.getById(id);
  getContent = (id: string): Promise<Buffer | null> => store.getContent(id);
  deleteGcode = (id: string): Promise<boolean> => store.delete(id);
}

export default new GcodeService();
