import type { PoolClient, QueryResult } from 'pg';
import { createHash } from 'node:crypto';
import persistence from './persistence.js';
import AppError from './error.js';
import { sanitiseFilename } from './file-helpers.js';
import type { GcodeFile, GcodeMetadata } from '../models/index.js';

/**
 * Metadata columns (no bytea). Bytea lives in `gcode_file_content` —
 * never JOINed for list/detail, only when the agent fetches the file.
 */
const GCODE_COLUMNS = `
  gf.id,
  gf.uploaded_by_user_id AS "uploadedByUserId",
  gf.original_filename AS "originalFilename",
  gf.sha256,
  gf.size_bytes AS "sizeBytes",
  gf.metadata,
  gf.created_at AS "createdAt"
`;

const GCODE_MAGIC_RE = /^[GM]\d+/m;

export interface UploadGcodeOptions {
  filename: string;
  buffer: Buffer;
  uploadedByUserId: string;
}

/**
 * Validates magic bytes so someone can't sneak a non-G-code binary past
 * our size limit. Parses the first chunk as UTF-8 and scans for any
 * `G<digit>` / `M<digit>` line — matches every slicer we've seen (Cura,
 * PrusaSlicer, OrcaSlicer), plus hand-rolled G-code.
 */
function assertGcodeMagic(buffer: Buffer): void {
  const probe = buffer.subarray(0, Math.min(buffer.length, 1024)).toString('utf8');
  if (!GCODE_MAGIC_RE.test(probe)) {
    throw AppError.badRequest(
      'Datei sieht nicht wie G-Code aus (erwartet G/M-Kommandos in den ersten 1 KB).',
      'BAD_GCODE_MAGIC'
    );
  }
}

/**
 * Parses the slicer-emitted comment headers every major slicer prints
 * at the top of the file. Best-effort — any missing field is just left
 * off the returned object. Only the first 64 KB are scanned.
 */
function parseMetadata(buffer: Buffer): GcodeMetadata {
  const head = buffer.subarray(0, Math.min(buffer.length, 65536)).toString('utf8');
  const md: GcodeMetadata = {};

  // Cura: `;TIME:1234`, PrusaSlicer: `; estimated printing time (normal mode) = 1h 23m 4s`
  const timeCura = /^;TIME:(\d+)/m.exec(head);
  if (timeCura) md.estimatedSeconds = Number.parseInt(timeCura[1], 10);
  if (md.estimatedSeconds === undefined) {
    const timePrusa = /estimated printing time[^=]*=\s*(?:(\d+)d\s*)?(?:(\d+)h\s*)?(?:(\d+)m\s*)?(?:(\d+)s)?/i.exec(head);
    if (timePrusa) {
      const [, d, h, m, s] = timePrusa;
      const total =
        (Number.parseInt(d || '0', 10) * 86400) +
        (Number.parseInt(h || '0', 10) * 3600) +
        (Number.parseInt(m || '0', 10) * 60) +
        Number.parseInt(s || '0', 10);
      if (total > 0) md.estimatedSeconds = total;
    }
  }

  const filament = /;Filament used:\s*([\d.]+)\s*m/i.exec(head) || /filament used \[mm\]\s*=\s*([\d.]+)/i.exec(head);
  if (filament) {
    const value = Number.parseFloat(filament[1]);
    md.filamentMeters = filament[0].includes('[mm]') ? value / 1000 : value;
  }

  const grams = /;Filament weight:\s*([\d.]+)/i.exec(head) || /filament used \[g\]\s*=\s*([\d.]+)/i.exec(head);
  if (grams) md.filamentGrams = Number.parseFloat(grams[1]);

  const layers = /;LAYER_COUNT:(\d+)/.exec(head) || /;\s*total layer number:\s*(\d+)/i.exec(head);
  if (layers) md.layerCount = Number.parseInt(layers[1], 10);

  const slicer = /;generated by\s+(\S+)/i.exec(head);
  if (slicer) md.slicer = slicer[1];

  return md;
}

export class GcodeService {
  /**
   * Validates, hashes, parses metadata, and writes both the metadata
   * row and the bytea blob atomically. Deduplicates on `sha256`: if the
   * same file was already uploaded, returns the existing row instead
   * of creating a duplicate content blob.
   */
  async uploadGcode(options: UploadGcodeOptions): Promise<GcodeFile> {
    const { filename, buffer, uploadedByUserId } = options;

    assertGcodeMagic(buffer);

    const cleanName = sanitiseFilename(filename, 'print.gcode');
    const sha256 = createHash('sha256').update(buffer).digest('hex');
    const metadata = parseMetadata(buffer);

    return this.withTx(async (client) => {
      // Dedup by hash. Owner can differ (A uploads `bracket.gcode`,
      // later B uploads the same bits) — we honour the first uploader
      // for attribution and skip the bytea round-trip.
      const existing: QueryResult<GcodeFile> = await client.query(
        `SELECT ${GCODE_COLUMNS} FROM public."gcode_file" gf WHERE gf.sha256 = $1`,
        [sha256]
      );
      if (existing.rows[0]) {
        return existing.rows[0];
      }

      const inserted = await client.query<{ id: string }>(
        `INSERT INTO public."gcode_file"
           (uploaded_by_user_id, original_filename, sha256, size_bytes, metadata)
         VALUES ($1::uuid, $2, $3, $4, $5::jsonb)
         RETURNING id`,
        [uploadedByUserId, cleanName, sha256, buffer.length, JSON.stringify(metadata)]
      );
      const fileId = inserted.rows[0].id;

      await client.query(
        `INSERT INTO public."gcode_file_content" (file_id, content)
         VALUES ($1::uuid, $2)`,
        [fileId, buffer]
      );

      const fresh: QueryResult<GcodeFile> = await client.query(
        `SELECT ${GCODE_COLUMNS} FROM public."gcode_file" gf WHERE gf.id = $1::uuid`,
        [fileId]
      );
      return fresh.rows[0];
    });
  }

  async listForUser(userId: string, limit = 50, offset = 0): Promise<GcodeFile[]> {
    const result: QueryResult<GcodeFile> = await persistence.database.query(
      `SELECT ${GCODE_COLUMNS}
       FROM public."gcode_file" gf
       WHERE gf.uploaded_by_user_id = $1::uuid
       ORDER BY gf.created_at DESC
       LIMIT $2 OFFSET $3`,
      [userId, limit, offset]
    );
    return result.rows;
  }

  async getById(id: string): Promise<GcodeFile | null> {
    const result: QueryResult<GcodeFile> = await persistence.database.query(
      `SELECT ${GCODE_COLUMNS} FROM public."gcode_file" gf WHERE gf.id = $1::uuid`,
      [id]
    );
    return result.rows[0] ?? null;
  }

  /**
   * Loads the binary content. Only called by the agent via a short-TTL
   * download ticket — user-facing endpoints never stream the bytea blob.
   */
  async getContent(id: string): Promise<Buffer | null> {
    const result: QueryResult<{ content: Buffer }> = await persistence.database.query(
      `SELECT content FROM public."gcode_file_content" WHERE file_id = $1::uuid`,
      [id]
    );
    return result.rows[0]?.content ?? null;
  }

  async deleteGcode(id: string): Promise<boolean> {
    // ON DELETE CASCADE wipes gcode_file_content; RESTRICT on print_job
    // guards against nuking a file that still has historical jobs
    // referencing it (Postgres will surface a 23503 → 409 in the
    // controller).
    const result = await persistence.database.query(
      `DELETE FROM public."gcode_file" WHERE id = $1::uuid`,
      [id]
    );
    return (result.rowCount ?? 0) > 0;
  }

  private async withTx<T>(fn: (client: PoolClient) => Promise<T>): Promise<T> {
    const client = await persistence.database.connect();
    try {
      await client.query('BEGIN');
      const result = await fn(client);
      await client.query('COMMIT');
      return result;
    } catch (err) {
      await client.query('ROLLBACK');
      throw err;
    } finally {
      client.release();
    }
  }
}

export default new GcodeService();
